services:
  - type: web
    name: api-hrt-indicacoes
    env: python
    plan: free
    region: virginia
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: banco-hrt-indicacoes
          property: internalConnectionString
      - key: PYTHON_VERSION
        value: 3.11.5